// --- ROOT SIGNATURE DEFINITION ---
// Global Root Signature:
// Slot 0: Output UAV (u0)
// Slot 1: TLAS (t0)
// Slot 2: Camera Constants (b0)

// --- RESOURCES ---
RWTexture2D<float4> gOutput : register(u0);
RaytracingAccelerationStructure gScene : register(t0);

cbuffer CameraData : register(b0)
{
    float4x4 viewProjInverse;
    float4 cameraPos;
};

// --- PAYLOAD ---
struct RayPayload
{
    float4 color;
};

// --- 1. RAY GENERATION SHADER ---
[shader("raygeneration")]
void MyRayGen()
{
    uint2 launchIndex = DispatchRaysIndex().xy;
    uint2 launchDim = DispatchRaysDimensions().xy;

    float2 uv = (launchIndex + 0.5f) / launchDim; // 0..1
    float2 screenPos = uv * 2.0f - 1.0f; // -1..1
    screenPos.y = -screenPos.y; // Flip Y

    // Unproject to find ray target
    // Note: viewProjInverse should be (View * Proj)^-1
    float4 target = mul(viewProjInverse, float4(screenPos, 1.0f, 1.0f));
    float3 rayDir = normalize(target.xyz / target.w - cameraPos.xyz);

    RayDesc ray;
    ray.Origin = cameraPos.xyz;
    ray.Direction = rayDir;
    ray.TMin = 0.001f;
    ray.TMax = 10000.0f;

    RayPayload payload;
    payload.color = float4(0, 0, 0, 0);

    TraceRay(
        gScene,
        RAY_FLAG_NONE,
        0xFF, // Mask
        0, // Hit Group Base Index (Opaque)
        0, // Multiplier (just 1 type for now)
        0, // Miss Shader Index
        ray,
        payload
    );

    gOutput[launchIndex] = payload.color;
}

// --- 2. MISS SHADER ---
[shader("miss")]
void MyMiss(inout RayPayload payload)
{
    // Sky color (Gradient blue)
    float3 rayDir = WorldRayDirection();
    float t = 0.5f * (rayDir.y + 1.0f);
    payload.color = float4(lerp(float3(1, 1, 1), float3(0.5, 0.7, 1.0), t), 1.0f);
}

// --- 3. CLOSEST HIT SHADER ---
// Attributes are generated by the intersection (barycentrics)
struct Attributes
{
    float2 bary;
};

[shader("closesthit")]
void MyClosestHit(inout RayPayload payload, in Attributes attr)
{
    // Visualize barycentrics for now (proof of geometry)
    // To do full PBR, we would need to access Vertex Buffers here using InstanceID()
    float3 baryColor = float3(1.0f - attr.bary.x - attr.bary.y, attr.bary.x, attr.bary.y);
    payload.color = float4(baryColor, 1.0f);
}